language: ruby
sudo: false
rvm: 2.6.1
cache: bundler
env:
  matrix:
    - SCRIPT="bundle exec rake build"
    - SCRIPT="bundle exec rake test"
script: $SCRIPT
# Notifications, used by our Gitter channel.
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9eef19829de6aa749075
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
