auto: true
server: true
markdown: kramdown
permalink: pretty
pygments: true

downloads:
  stable: 
    version: 1.9.3-p385
    url: http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-p385.tar.gz
    md5: 3e0d7f8512400c1a6732327728a56f1d
  stable_snapshot:
    url: http://ftp.ruby-lang.org/pub/ruby/ruby-1.9-stable.tar.gz
  nightly_snapshot:
    url: http://ftp.ruby-lang.org/pub/ruby/snapshot.tar.gz

top_projects:
  - name: FLVTool2
    url: http://rubyforge.org/projects/flvtool2/
    description: |
      FLVTool2 is a manipulation tool for Macromedia Flash Video files (FLV).
      It can calculate a lot of meta data, insert an onMetaData tag, cut FLV
      files, add cue points (onCuePoint), show the FLV structure and print
      meta data information in XML or YAML.

  - name: Ruby Enterprise Edition
    url: http://rubyforge.org/projects/emm-ruby/
    description: |
      Ruby Enterprise Edition is a branch of Ruby, which includes an enhanced
      garbage collector and developer tools. This allows one to reduce memory
      usage of Ruby on Rails applications by 33% on average.

  - name: SQLite-Ruby
    url: http://rubyforge.org/projects/sqlite-ruby/
    description: |
      A Ruby interface for the SQLite database engine.

  - name: Ruby/DBI
    url: http://rubyforge.org/projects/ruby-dbi/
    description: |
      Ruby/DBI develops a database independent interface for accessing
      databases - similar to Perl's DBI.

  - name: Watir
    url: http://rubyforge.org/projects/wtr/
    description: |
      Watir is a testing tool for automating browser-based tests of web
      applications. It is a Ruby library that works with Internet Explorer
      and Firefox.

locales:
  sitelinks:
    en:
      - text: Downloads
        url:  downloads
      - text: Documentation
        url:  documentation
      - text: Libraries
        url:  libraries
      - text: Community
        url:  community
      - text: News
        url:  news
      - text: Security
        url:  security
      - text: About Ruby
        url:  about
    bg:
      - text: За сваляне
        url: downloads
      - text: Документация
        url: documentation
      - text: Библиотеки
        url: libraries
      - text: Общество
        url: community
      - text: Новини
        url: news
      - text: Сигурност
        url: security
      - text: Относно
        url: about
    de:
      - text: Downloads
        url:  downloads
      - text: Dokumentation
        url:  documentation
      - text: Bibliotheken
        url:  libraries
      - text: Community
        url:  community
      - text: Neuigkeiten
        url:  news
      - text: Sicherheit (en)
        url:  /en/security
      - text: Über Ruby
        url:  about
    es:
      - text: Descargas
        url:  downloads
      - text: Documentación
        url:  documentation
      - text: Bibliotecas
        url:  libraries
      - text: Comunidad
        url:  community
      - text: Noticias
        url:  news
      # - text: Seguridad
      #   url:  security
      - text: Acerca de Ruby
        url:  about
    fr:
      - text: Téléchargements
        url:  downloads
      - text: Documentation
        url:  documentation
      - text: Bibliothèques
        url:  libraries
      - text: Communauté
        url:  community
      - text: Actualités
        url:  news
      - text: Sécurité
        url:  security
      - text: À propos de Ruby
        url:  about
    id:
      - text: Download
        url: downloads
      - text: Dokumentasi
        url: documentation
      - text: Library
        url: libraries
      - text: Komunitas
        url: community
      - text: Berita
        url: news
      - text: Tentang Ruby
        url: about
    it:
      - text: Scarica
        url:  downloads
      - text: Documentazione
        url:  documentation
      - text: Librerie
        url:  libraries
      - text: Comunità
        url:  community
      - text: Notizie
        url:  news
      - text: Sicurezza
        url:  security
      - text: A proposito di Ruby
        url:  about
    ja:
      - text: ダウンロード
        url: downloads
      - text: ドキュメント
        url: documentation
      - text: ライブラリ
        url: libraries
      - text: コミュニティ
        url: community
      - text: コア開発
        url: dev
      - text: ニュース
        url: news
      - text: セキュリティ
        url: security
      - text: Rubyとは
        url: about
    ko:
      - text: 다운로드
        url: downloads
      - text: 문서
        url: documentation
      - text: 라이브러리
        url: libraries
      - text: 커뮤니티
        url: community
      - text: 뉴스
        url: news
      - text: 보안이슈
        url: security
      - text: 루비에 대해서
        url: about
    pl:
      - text: Pobierz
        url: downloads
      - text: Dokumentacja
        url: dokumentacja
      - text: Biblioteki
        url: libraries
      - text: Społeczność
        url: spolecznosc
      - text: Wiadomości
        url: news
      - text: O języku Ruby
        url: about
    pt:
      - text:  Downloads
        url: downloads
      - text: Documentação
        url: documentacao
      - text: Módulos
        url: bibliotecas
      - text: Comunidade
        url: comunidade
      - text: Notícias
        url: noticias-recentes
      - text: Sobre Ruby
        url: sobre-o-ruby
    tr:
      - text: İndirin
        url: downloads
      - text: Belgeler
        url: documentation
      - text: Kütüphaneler
        url: libraries
      - text: Topluluk
        url: community
      - text: Haberler
        url: news
      - text: Güvenlik
        url: security
      - text: Ruby Hakkında
        url: about
    zh_cn:
      - text: 下载
        url: downloads
      - text: 文档
        url: documentation
      - text: 资源库
        url: libraries
      - text: 社区
        url: community
      - text: 新闻
        url: news
      - text: 安全
        url: security
      - text: 关于 Ruby
        url: about
    zh_TW:
      - text: 下載安裝
        url: downloads
      - text: 文件
        url: documentation
      - text: 函式庫
        url: libraries
      - text: 社群
        url: community
      - text: 新聞
        url: news
      - text: 安全
        url: security
      - text: 關於 Ruby
        url: about

  sidebar:
    try_ruby: &try_ruby
      url: http://tryruby.org/
    books: &books
      url: http://www.amazon.com/s/ref=sr_nr_n_5?ie=UTF8&rs=1000&keywords=Ruby&rh=i%3Aaps%2Ck%3ARuby%2Ci%3Astripbooks%2Cn%3A1000%2Cn%3A5

    en:
      get_started:
        text: <strong>Get Started</strong>, it's easy!
        try_ruby:
          text: Try Ruby! (in your browser)
          <<: *try_ruby
        quickstart:
          text: Ruby in Twenty Minutes
          url: documentation/quickstart/
        ruby_from_other_languages:
          text: Ruby from Other Languages
          url: documentation/ruby-from-other-languages/
      explore:
        text: <strong>Explore</strong> a new world…
        documentation:
          text: Documentation
          url: documentation/
        books:
          text: Books
          <<: *books
        libraries:
          text: Libraries
          url: libraries/
        success_stories:
          text: Success Stories
          url: documentation/success-stories/
      participate:
        text: <strong>Participate</strong> in a friendly and growing community.
        mailing_lists:
          text: Mailing Lists
          url: community/mailing-lists/
          description: |
            Talk about Ruby with programmers from all around the world.
        user_groups:
          text: User Groups
          url: community/user-groups/
          description: |
            Get in contact with Rubyists in your area.
        weblogs:
          text: Weblogs
          url: community/weblogs/
          description: |
            Read about what’s happening right now in the Ruby community.
        ruby_core:
          text: Ruby Core
          url: community/ruby-core/
          description: |
            Help polish the rough edges of the latest Ruby.
        issue_tracking:
          text: Issue Tracking
          url: https://bugs.ruby-lang.org/
          description: |
            Report or help solve issues in Ruby.
      top_ruby_projects:
        text: Some Top Ruby Projects
        more:
          text: More…
          url: libraries/top-projects/
      syndicate:
        text: Syndicate
        recent_news:
          text: Recent News (RSS)
          url: feeds/news.rss
    bg:
      get_started:
        text: <strong>Започнете</strong> лесно е!
        try_ruby:
          text: Пробвайте Ruby! (в браузъра)
          <<: *try_ruby
        quickstart:
          text: Ruby в 20 минути
          url: documentation/quickstart/
        ruby_from_other_languages:
          text: Ruby от други езици
          url: documentation/ruby-from-other-languages/
      explore:
        text: <strong>Изследвайте</strong> нов свят…
        documentation:
          text: Документация
          url: documentation/
        books:
          text: Книги
          <<: *books
        libraries:
          text: Библиотеки
          url: libraries/
        success_stories:
          text: Успешни истории
          url: documentation/success-stories/
      participate:
        text: <strong>Участвайте</strong> в приятелски настроено общество.
        mailing_lists:
          text: Пощенски списъци
          url: community/mailing-lists/
          description: |
            Дискусии относно Ruby с програмисти от цял свят.
        user_groups:
          text: Потребителски групи
          url: community/user-groups/
          description: |
            Свържете се с рубисти в твоя район.
        weblogs:
          text: Блогове
          url: community/weblogs/
          description: |
            Прочетете какво се случва в Ruby обществото.
        ruby_core:
          text: Ruby ядро
          url: community/ruby-core/
          description: |
            Помогнете за разработката на Ruby.
        issue_tracking:
          text: Следене на бъгове
          url: https://bugs.ruby-lang.org/
          description: |
            Докладвайте или помогнете за решаването на проблеми в Ruby.
      top_ruby_projects:
        text: Няколко топ Ruby проекта
        more:
          text: Още…
          url: libraries/top-projects/
      syndicate:
        text: Новини
        recent_news:
          text: Последните новини (RSS)
          url: feeds/news.rss
    de:
      get_started:
        text: <strong>Der Einstieg</strong> ist einfach!
        try_ruby:
          text: Teste Ruby! (im Browser)
          <<: *try_ruby
        quickstart:
          text: Ruby in 20 Minuten
          url: documentation/quickstart/
        ruby_from_other_languages:
          text: Ruby für Umsteiger
          url: documentation/ruby-from-other-languages/
      explore:
        text: <strong>Entdecke</strong> eine neue Welt…
        documentation:
          text: Dokumentation
          url: documentation/
        books:
          text: Bücher
          <<: *books
        libraries:
          text: Bibliotheken
          url: libraries/
        success_stories:
          text: Erfolgsgeschichten
          url: documentation/success-stories/
      participate:
        text: <strong>Beteilige dich</strong> an einer freundlichen und wachsenden Community.
        mailing_lists:
          text: Mailing-Listen
          url: community/mailing-lists/
          description: |
            Sprich mit Programmierern auf der ganzen Welt über Ruby.
        user_groups:
          text: User-Groups
          url: community/user-groups/
          description: |
            Treffe Rubyisten in deiner Umgebung.
        weblogs:
          text: Weblogs
          url: community/weblogs/
          description: |
            Lies, was gerade jetzt in der Ruby-Community passiert.
        ruby_core:
          text: Ruby-Entwicklung
          url: community/ruby-core/
          description: |
            Hilf mit, die neuesten Ruby-Versionen zu verbessern.
        issue_tracking:
          text: Fehler melden
          url: https://bugs.ruby-lang.org/
          description: |
            Melde einen Fehler oder hilf mit, offene Fehler zu beseitigen.
      top_ruby_projects:
        text: Beliebte Ruby-Projekte
        more:
          text: Mehr…
          url: libraries/top-projects/
      syndicate:
        text: Syndication
        recent_news:
          text: Aktuelle Neuigkeiten (RSS)
          url: feeds/news.rss

  credits:
    en: |
      This website was generated with Ruby using <a href="http://www.jekyllrb.com/">Jekyll</a>.
      It is proudly maintained by <a href="http://rubyidentity.org">members of the Ruby community</a>.
      Please contact our <a href="mailto:webmaster@ruby-lang.org">webmaster</a>
      for questions or comments concerning this website.
    de: |
      Diese Webseite wurde mit Ruby unter Verwendung von <a href="http://www.jekyllrb.com/">Jekyll</a> erstellt.
      Sie wird mit Stolz von <a href="http://rubyidentity.org">Mitgliedern der Ruby-Community</a> gepflegt.
      Bei Fragen oder Kommentaren, die diese Seite betreffen, kontaktieren Sie bitte
      unseren <a href="mailto:webmaster@ruby-lang.org">Webmaster</a> (in Englisch).
    es: |
      Este sitio web está desarrollado con Ruby y <a href="http://www.jekyllrb.com/">Jekyll</a>.
      Es orgullosamente mantenido por <a href="http://rubyidentity.org">miembros de la comunidad Ruby</a>.
      Por favor contacta a nuestro <a href="mailto:webmaster@ruby-lang.org">webmaster</a>
      si tienes preguntas o comentarios al respecto del sitio web.
    fr: |
      Ce site est propulsé par Ruby et <a href="http://www.jekyllrb.com/">Jekyll</a>.
      Il est fièrement maintenu par des <a href="http://rubyidentity.org">membres de la communauté Ruby</a>.
      Veuillez contacter notre <a href="mailto:webmaster@ruby-lang.org">webmaster</a>
      pour toute question ou tout commentaire le concernant.
    it: |
      Questo sito è stato sviluppato con Ruby e <a href="http://www.jekyllrb.com/">Jekyll</a>.
      È curato con dedizione dai <a href="http://rubyidentity.org">membri della comunità di Ruby</a>.
      Puoi contattare il nostro <a href="mailto:webmaster@ruby-lang.org">webmaster</a>
      per domande e commenti riguardanti questo sito.
