auto: true
server: true
markdown: kramdown
permalink: date
pygments: true

downloads:
  source:
    - name: Ruby 1.9.2-p290
      url: http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.2-p290.tar.gz
      md5: 604da71839a6ae02b5b5b5e1b792d5eb
      comment: Stable Version (_recommended_)
    - name: Ruby 1.9.3 preview1
      url: http://ftp.ruby-lang.org/pub/ruby/1.9/ruby-1.9.3-preview1.tar.gz
      md5: 0f0220be4cc7c51a82c1bd8f6a0969f3
    - name: Stable Snapshot
      url: http://ftp.ruby-lang.org/pub/ruby/ruby-1.9-stable.tar.gz
      comment: |
        This is tar&#8217;ed and gzip&#8217;ed file of the latest stable SVN.
        It should be better than the last stable release.
    - name: Nightly Snapshot
      url: http://ftp.ruby-lang.org/pub/ruby/snapshot.tar.gz
      comment: |
        This is tar&#8217;ed and gzip&#8217;ed file of the latest SVN.
        It may contain unfixed problems.

  windows:
    - name: Ruby 1.8.6-p398 RubyInstaller
      url: http://rubyforge.org/frs/download.php/71066/rubyinstaller-1.8.6-p398.exe
      md5: 233d6b3ddc4c61436b075b51254cd138
      comment: Stable version
    - name: Ruby 1.8.7-p334 RubyInstaller
      url: http://rubyforge.org/frs/download.php/74293/rubyinstaller-1.8.7-p334.exe
      md5: 64e30e63e16028282fcfe3ec57b561dc
      comment: Stable version (_recommended_)
    - name: Ruby 1.9.1-p430 RubyInstaller
      url: http://rubyforge.org/frs/download.php/72075/rubyinstaller-1.9.1-p430.exe
      md5: 86ac589a955898c3163b161d81750a05
      comment: Stable version
    - name: Ruby 1.9.2-p180 RubyInstaller
      url: http://rubyforge.org/frs/download.php/74298/rubyinstaller-1.9.2-p180.exe
      md5: 2c94aef50987416d64c85a4ea0fa428b
      comment: Stable version (_recommended_)
    - name: Ruby 1.8.7-p249 Binary
      url: http://ftp.ruby-lang.org/pub/ruby/binaries/mswin32/ruby-1.8.7-p249-i386-mswin32.zip
      md5: 4fd37b0b4b21a042cae7f5f0a8daad16
      comment: Stable version
    - name: Ruby 1.9.1-p378 Binary
      url: http://ftp.ruby-lang.org/pub/ruby/binaries/mswin32/ruby-1.9.1-p378-i386-mswin32.zip
      md5: 7d14a918cc8d243d3e2c409aff41f454
      comment: Stable version

top_projects:
  - name: FLVTool2
    url: http://rubyforge.org/projects/flvtool2/
    description: |
      FLVTool2 is a manipulation tool for Macromedia Flash Video files (FLV).
      It can calculate a lot of meta data, insert an onMetaData tag, cut FLV
      files, add cue points (onCuePoint), show the FLV structure and print
      meta data information in XML or YAML.

  - name: Ruby Enterprise Edition
    url: http://rubyforge.org/projects/emm-ruby/
    description: |
      Ruby Enterprise Edition is a branch of Ruby, which includes an enhanced
      garbage collector and developer tools. This allows one to reduce memory
      usage of Ruby on Rails applications by 33% on average.

  - name: SQLite-Ruby
    url: http://rubyforge.org/projects/sqlite-ruby/
    description: |
      A Ruby interface for the SQLite database engine.

  - name: Ruby/DBI
    url: http://rubyforge.org/projects/ruby-dbi/
    description: |
      Ruby/DBI develops a database independent interface for accessing
      databases - similar to Perl's DBI.

  - name: Watir
    url: http://rubyforge.org/projects/wtr/
    description: |
      Watir is a testing tool for automating browser-based tests of web
      applications. It is a Ruby library that works with Internet Explorer
      and Firefox.

